module.exports = {
    attributes: {
      name: { type: 'string' },
      arrestTime: { type: 'number', required: true },
      location: { type: 'string', required: true },
      offence: { type: 'string' },
      termsOfRelease: { type: 'string' },
      charges: { type: 'string' },
      bailConditions: { type: 'string' },
      courtDate: { type: 'string' },
      courtLocation: { type: 'string' },
      policeStation: { type: 'string' },
      localXRGroup: { type: 'string' },
      nearestCity: { type: 'string' },
      injuries: { type: 'string' },
      adverseEvents: { type: 'string' },
      heldMoreThan24Hours: { type: 'boolean', defaultsTo: false },
      helpNeeded: { type: 'string' },
      specialRequest: { type: 'string' },
      numberRebels: { type: 'number' },
      rebelsStillHeld: { type: 'number' },
      email: { type: 'string' },
      phone: { type: 'string' },
      canShareWithLocalXRGroup: { type: 'boolean', defaultsTo: false },
      comment: { type: 'string' },
      isHidden: { type: 'boolean', defaultsTo: false },
    },
  };