module.exports = {
    attributes: {
      name: { type: 'string' },
      arrestTime: {
        type: 'ref',
        columnType: 'timestamptz',
        required: true,
      },
      location: { type: 'string', required: true },
      offence: { type: 'string' },
      termsOfRelease: { type: 'string' },
      charges: { type: 'string' },
      bailConditions: { type: 'string' },
      courtDate: { type: 'string' },
      courtLocation: { type: 'string' },
      policeStation: { type: 'string' },
      nearestCity: { type: 'string' },
      injuries: { type: 'string' },
      adverseEvents: { type: 'string' },
      heldMoreThan24Hours: { type: 'boolean', defaultsTo: false },
      helpNeeded: { type: 'string' },
      specialRequest: { type: 'string' },
      numberRebels: { type: 'number' },
      accusedOf: { type: 'string' },
      plea: { type: 'string' },
      furtherHearings: { type: 'string' },
      solicitor: { type: 'string' },
      actionGroup: { type: 'string' },
      xrRegion: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string' },
      comment: { type: 'string' },
      isHidden: { type: 'boolean', defaultsTo: false },
    },
  };