version: "3"

services:
    backoffice:
        build: .
        ports:
            - "8080:8080"
            - "9229:9229"
        environment:
            NODE_ENV: "production"
            BASE_HOSTNAME: "arrestwatch.info:8088"
            sails_datastores__default__adapter: "sails-postgresql"
            sails_datastores__default__url: "postgresql://postgres:hunter12@db:5432/postgres"
            sails_session__url: "redis://redis:6379/0"
            sails_custom__killSwitchToken: "SomeRandomToken"
        depends_on:
            - "db"
            - "redis"
    backend-api:
        build: backend-django
        ports:
            - "8082:8080"
        environment:
            BACKOFFICE_SECRET_KEY: "fD3W^R6T*U$r3KnCaiW7"
            BACKOFFICE_DB_ENGINE: django.db.backends.postgresql_psycopg2
            BACKOFFICE_DB_NAME: postgres
            BACKOFFICE_DB_USER: postgres
            BACKOFFICE_DB_PASSWORD: hunter12
            BACKOFFICE_DB_HOST: db
            BACKOFFICE_DB_PORT: 5432
        depends_on:
            - "db"
            - "redis"
    nginx:
        build: nginx
        ports:
            - "8088:80"
            - "8083:443"
        depends_on:
            - "backoffice"
            - "backend-api"
    db:
        build:
            context: backend
            dockerfile: Dockerfile.db
        environment:
            POSTGRES_PASSWORD: hunter12
    redis:
        image: "redis:6"