
exports.up = async function(knex) {
  await knex.schema.createTable('user', function (table) {
      table.bigInteger('createdAt')
      table.bigInteger('updatedAt')
      table.increments('id')
      table.text('username')
      table.text('password')
      table.text('nickname')
      table.float('expires')
      table.float('lastSeenAt')
      table.boolean('isAdmin')
      table.boolean('canViewRelease')
  })
  await knex.schema.createTable('witness', function (table) {
      table.bigInteger('createdAt')
      table.bigInteger('updatedAt')
      table.increments('id')
      table.text('witnessEmail')
  })
  await knex.schema.createTable('report', function (table) {
      table.bigInteger('createdAt')
      table.bigInteger('updatedAt')
      table.increments('id')
      table.text('station')
      table.float('arrestTime')
      table.text('location')
      table.text('name')
      table.text('arrestingOfficerId')
      table.boolean('concernMentalDistress')
      table.boolean('concernPhysicalDistress')
      table.boolean('concernMinor')
      table.boolean('concernPoliceBehaviour')
      table.boolean('concernPolicePrejudice')
      table.boolean('concernMedicationNeed')
      table.text('medicationName')
      table.text('observations')
      table.text('comment')
      table.integer('witness')
      table.boolean('isHidden')
  })
  await knex.schema.createTable('release', function (table) {
      table.bigInteger('createdAt')
      table.bigInteger('updatedAt')
      table.increments('id')
      table.text('name')
      table.float('arrestTime')
      table.text('location')
      table.text('offence')
      table.text('termsOfRelease')
      table.text('charges')
      table.text('bailConditions')
      table.text('courtDate')
      table.text('courtLocation')
      table.text('policeStation')
      table.text('localXRGroup')
      table.text('nearestCity')
      table.text('injuries')
      table.text('adverseEvents')
      table.text('heldMoreThan24Hours')
      table.text('helpNeeded')
      table.text('specialRequest')
      table.float('numberRebels')
      table.float('rebelsStillHeld')
      table.text('email')
      table.text('phone')
      table.boolean('canShareWithLocalXRGroup')
      table.text('comment')
      table.boolean('isHidden')
  })
  await knex.schema.createTable('calllog', function (table) {
      table.bigInteger('createdAt')
      table.bigInteger('updatedAt')
      table.increments('id')
      table.text('comment')
      table.integer('createdBy')
      table.boolean('isHidden')
  })
  await knex.schema.createTable('legalobserverlog', function (table) {
      table.bigInteger('createdAt')
      table.bigInteger('updatedAt')
      table.increments('id')
      table.text('name')
      table.text('phone')
      table.boolean('onShift')
      table.integer('createdBy')
      table.boolean('isHidden')
  })
};

exports.down = async function(knex) {
  await knex.schema.dropTable('user')
  await knex.schema.dropTable('witness')
  await knex.schema.dropTable('report')
  await knex.schema.dropTable('release')
  await knex.schema.dropTable('calllog')
  await knex.schema.dropTable('legalobserverlog')
};
