# Generated by Django 3.0.2 on 2020-01-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('validTo', models.DateTimeField()),
                ('court', models.TextField()),
                ('date', models.DateTimeField()),
                ('bench', models.TextField()),
                ('defendantName', models.TextField()),
                ('defendantNumber', models.TextField()),
                ('charges', models.TextField()),
                ('representation', models.TextField()),
                ('outline', models.TextField()),
                ('evidenceSubmitted', models.TextField()),
                ('evidenceInPerson', models.TextField()),
                ('verdict', models.TextField()),
                ('sentence', models.TextField()),
                ('costs', models.TextField()),
                ('notes', models.TextField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Identity')),
            ],
        ),
    ]
