# Generated by Django 3.1.5 on 2021-01-29 23:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.TextField()),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('verified', models.BooleanField()),
                ('rejected', models.BooleanField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.stationregion')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('arrestTime', models.DateTimeField()),
                ('location', models.TextField()),
                ('name', models.TextField()),
                ('arrestingOfficerId', models.TextField()),
                ('consentToContact', models.BooleanField()),
                ('concernMentalDistress', models.BooleanField()),
                ('concernPhysicalDistress', models.BooleanField()),
                ('concernMinor', models.BooleanField()),
                ('concernPoliceBehaviour', models.BooleanField()),
                ('concernPolicePrejudice', models.BooleanField()),
                ('concernMedicationNeed', models.BooleanField()),
                ('medicationName', models.TextField()),
                ('concernHandcuffs', models.BooleanField()),
                ('observations', models.TextField()),
                ('comment', models.TextField()),
                ('isHS2Action', models.BooleanField()),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.station')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.identity')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('arrestTime', models.DateTimeField()),
                ('location', models.TextField()),
                ('offence', models.TextField()),
                ('termsOfRelease', models.TextField()),
                ('charges', models.TextField()),
                ('bailConditions', models.TextField()),
                ('courtDate', models.TextField()),
                ('courtLocation', models.TextField()),
                ('localXRGroup', models.TextField()),
                ('nearestCity', models.TextField()),
                ('injuries', models.TextField()),
                ('adverseEvents', models.TextField()),
                ('heldMoreThan24Hours', models.BooleanField()),
                ('helpNeeded', models.TextField()),
                ('specialRequest', models.TextField()),
                ('numberRebels', models.IntegerField()),
                ('rebelsStillHeld', models.IntegerField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('canShareWithLocalXRGroup', models.BooleanField()),
                ('canShareWithXRPress', models.BooleanField()),
                ('comment', models.TextField()),
                ('isHS2Action', models.BooleanField()),
                ('isPartOfXR', models.BooleanField()),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.identity')),
                ('policeStation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.station')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PleaHearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('hometown', models.TextField()),
                ('charge', models.TextField()),
                ('lawFirm', models.TextField()),
                ('consentToContact', models.BooleanField()),
                ('canShareWithLocalXRGroup', models.BooleanField()),
                ('consentToRecord', models.BooleanField()),
                ('consentToPress', models.BooleanField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.identity')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('court', models.TextField()),
                ('date', models.DateTimeField()),
                ('bench', models.TextField()),
                ('defendantName', models.TextField()),
                ('defendantNumber', models.TextField()),
                ('charges', models.TextField()),
                ('representation', models.TextField()),
                ('outline', models.TextField()),
                ('evidenceSubmitted', models.TextField()),
                ('evidenceInPerson', models.TextField()),
                ('verdict', models.TextField()),
                ('sentence', models.TextField()),
                ('costs', models.TextField()),
                ('notes', models.TextField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.identity')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalObserverLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
