# Generated by Django 3.0.2 on 2020-01-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='validTo',
            field=models.DateTimeField(null=True),
        ),
    ]
