# Generated by Django 3.0.2 on 2020-01-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20200109_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PleaHearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('validTo', models.DateTimeField(null=True)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('hometown', models.TextField()),
                ('charge', models.TextField()),
                ('lawFirm', models.TextField()),
                ('consentToContact', models.BooleanField()),
                ('canShareWithLocalXRGroup', models.BooleanField()),
                ('consentToRecord', models.BooleanField()),
                ('consentToPress', models.BooleanField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Identity')),
            ],
        ),
    ]
