# Generated by Django 3.0.2 on 2020-08-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_pleahearing'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('verified', models.BooleanField()),
                ('rejected', models.BooleanField()),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.StationRegion')),
            ],
        ),
    ]
