# Generated by Django 3.1.5 on 2021-02-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_create_release_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalobserverlog',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalobserverlog',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalobserverlog',
            name='onShift',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalobserverlog',
            name='phone',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
