# Generated by Django 3.1.5 on 2021-03-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20210201_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='consentToContact',
        ),
    ]
