# Generated by Django 3.1.5 on 2021-01-29 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backoffice', '0005_station_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='pleahearing',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='stationregion',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.RemoveField(
            model_name='observation',
            name='validTo',
        ),
        migrations.RemoveField(
            model_name='pleahearing',
            name='validTo',
        ),
        migrations.AddField(
            model_name='identity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pleahearing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stationregion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('arrestTime', models.DateTimeField()),
                ('location', models.TextField()),
                ('name', models.TextField()),
                ('arrestingOfficerId', models.TextField()),
                ('consentToContact', models.BooleanField()),
                ('concernMentalDistress', models.BooleanField()),
                ('concernPhysicalDistress', models.BooleanField()),
                ('concernMinor', models.BooleanField()),
                ('concernPoliceBehaviour', models.BooleanField()),
                ('concernPolicePrejudice', models.BooleanField()),
                ('concernMedicationNeed', models.BooleanField()),
                ('medicationName', models.TextField()),
                ('concernHandcuffs', models.BooleanField()),
                ('observations', models.TextField()),
                ('comment', models.TextField()),
                ('isHS2Action', models.BooleanField()),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.station')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.identity')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('arrestTime', models.DateTimeField()),
                ('location', models.TextField()),
                ('offence', models.TextField()),
                ('termsOfRelease', models.TextField()),
                ('charges', models.TextField()),
                ('bailConditions', models.TextField()),
                ('courtDate', models.TextField()),
                ('courtLocation', models.TextField()),
                ('localXRGroup', models.TextField()),
                ('nearestCity', models.TextField()),
                ('injuries', models.TextField()),
                ('adverseEvents', models.TextField()),
                ('heldMoreThan24Hours', models.BooleanField()),
                ('helpNeeded', models.TextField()),
                ('specialRequest', models.TextField()),
                ('numberRebels', models.IntegerField()),
                ('rebelsStillHeld', models.IntegerField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('canShareWithLocalXRGroup', models.BooleanField()),
                ('canShareWithXRPress', models.BooleanField()),
                ('comment', models.TextField()),
                ('isHS2Action', models.BooleanField()),
                ('isPartOfXR', models.BooleanField()),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.identity')),
                ('policeStation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.station')),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalObserverLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
